AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  restaurant-assistant

  Sample SAM Template for restaurant-assistant

Resources:
  RestaurantAssistantFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src
      Handler: server_lambda.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        RestaurantAssistant:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /question
            Method: get

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RestaurantAssistantApi:
    Description: API Gateway endpoint URL for Prod stage for Restaurant Assistant function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/question/"
  RestaurantAssistantFunction:
    Description: Restaurant Assistant Lambda Function ARN
    Value: !GetAtt RestaurantAssistantFunction.Arn
  RestaurantAssistantFunctionIamRole:
    Description: Implicit IAM Role created for Restaurant Assistant function
    Value: !GetAtt RestaurantAssistantFunctionRole.Arn
